### ISSUE TITLE
Expected Output component not vertically aligned

### ISSUE THREAD

**Issue by anyaparekh** [openclimatefix/pv-sites-mobile#201]
**Describe the bug**
The text in the expected output component on the dashboard page is not vertically aligned. However, both the expected output component and sunny time frame render the same component (NumberDisplay), yet only the expected output component is misaligned.

Refer to `components\dashboard-modules\ExpectedTotalOutput.tsx` to see the issue with the NumberDisplay render
```const ExpectedTotalOutput: FC<{ siteUUID: string }> = ({ siteUUID }) => {
  const { forecastData } = useSiteData(siteUUID);
  return (
    <NumberDisplay
      title="Today's Expected Output"
      value={
        forecastData
          ? getTotalExpectedOutput(forecastData.forecast_values)
              .toFixed(2)
              .toString() + ' kWh'
          : 'Loading'
      }
    />
  );
};
```

**To Reproduce**

1. Go to dashboard page
2. View the Expected Output component
3. See error

**Expected behavior**
The text within the component should be vertically aligned #

**Comment by ashayp22** [comment]
This is occurring because of [<NumberDisplay/>'s](Element) Element component.` <ExpectedTotalOutput/>` doesn't pass an onClick prop to <NumberDisplay/>, while <SunnyTimeframe/> does. This causes the former's component to be rendered with a **div**, and the latter with a **button**. **div** and **button** has different styles, causing the positioning difference.

I suggest we either remove the **button** component and replace it with a **div**, add additional styling when choosing a div so that it matches the **button** default styling, or remove the **onClick** functionality because as @ericcccsliu mentioned, it isn't intended to have any impact on the end-user and serves as an Easter Egg.
